# Data Cleaning

## Adult Literacy Rate

In [323]:
import pandas as pd

df_alit = pd.read_csv("../data/un_processed/adult_literacy_rate.csv")

In [324]:
df_alit.columns

Index(['entity', 'code', 'year',
       'adult_literacy_rate__population_15plus_years__both_sexes__pct__lr_ag15t99'],
      dtype='str')

In [325]:
df_alit.columns = ['country', 'code', 'year', 'adult_literacy']

In [326]:
print(df_alit['country'].unique().tolist())

['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Angola', 'Anguilla', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba', 'Azerbaijan', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon', 'Cape Verde', 'Cayman Islands', 'Central African Republic', 'Central and Southern Asia (SDG)', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Democratic Republic of Congo', 'Dominican Republic', 'East Asia and Pacific (WB)', 'East Timor', 'Eastern and South-Eastern Asia (SDG)', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Europe and Central Asia (WB)', 'Europe and Northern America (SDG)', 'French Guiana', 'Gabon', 'Gambia', 'Georgia', 'Ghana', 'Greece', 'Grenada', 'Guadeloupe', 'Guam', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hungary', 'India', 'Indonesia', 'Iran', 'Iraq', 'Israel', 'Italy', 'Jamaica', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latin America and Caribbean (WB)', 'Latin America and the Caribbean (SDG)', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Lithuania', 'Low-income countries', 'Lower-middle-income countries', 'Macao', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Martinique', 'Mauritania', 'Mauritius', 'Mexico', 'Middle East and North Africa (WB)', 'Middle-income countries', 'Moldova', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'New Caledonia', 'Nicaragua', 'Niger', 'Nigeria', 'North America (WB)', 'North Korea', 'North Macedonia', 'Northern Africa and Western Asia (SDG)', 'Oceania (excluding Australia and New Zealand) (SDG)', 'Oman', 'Pakistan', 'Palau', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar', 'Reunion', 'Romania', 'Russia', 'Rwanda', 'Saint Helena', 'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Asia (WB)', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sub-Saharan Africa (SDG)', 'Sub-Saharan Africa (WB)', 'Sudan', 'Suriname', 'Syria', 'Tajikistan', 'Tanzania', 'Thailand', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Uganda', 'Ukraine', 'United Arab Emirates', 'Upper-middle-income countries', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam', 'World', 'Yemen', 'Zambia', 'Zimbabwe']

In [327]:
remove_list = [
    "World",
    "Low-income countries",
    "Lower-middle-income countries",
    "Upper-middle-income countries",
    "Middle-income countries",
    "Central and Southern Asia (SDG)",
    "East Asia and Pacific (WB)",
    "Eastern and South-Eastern Asia (SDG)",
    "Europe and Central Asia (WB)",
    "Europe and Northern America (SDG)",
    "Latin America and Caribbean (WB)",
    "Latin America and the Caribbean (SDG)",
    "Middle East and North Africa (WB)",
    "North America (WB)",
    "Northern Africa and Western Asia (SDG)",
    "Oceania (excluding Australia and New Zealand) (SDG)",
    "South Asia (WB)",
    "Sub-Saharan Africa (SDG)",
    "Sub-Saharan Africa (WB)",
    "High-income countries"
]

df_alit = df_alit[~df_alit["country"].isin(remove_list)]

In [328]:
df_alit.isnull().sum()

country           0
code              0
year              0
adult_literacy    0
dtype: int64

In [329]:
df_alit.shape

(948, 4)

In [330]:
df_alit.to_csv("../data/processed/adult_literacy_rate_p.csv", index = False)

## Youth Literacy Rate

In [331]:
df_ylit = pd.read_csv("../data/un_processed/youth_literacy_rate.csv")

In [332]:
df_ylit.columns = ['country', 'code', 'year', 'youth_literacy_m', 'youth_literacy_f', 'region']

In [333]:
df_ylit.columns

Index(['country', 'code', 'year', 'youth_literacy_m', 'youth_literacy_f',
       'region'],
      dtype='str')

In [334]:
remove_list = [
    "World",
    "Low-income countries",
    "Lower-middle-income countries",
    "Upper-middle-income countries",
    "Middle-income countries",
    "Central and Southern Asia (SDG)",
    "East Asia and Pacific (WB)",
    "Eastern and South-Eastern Asia (SDG)",
    "Europe and Central Asia (WB)",
    "Europe and Northern America (SDG)",
    "Latin America and Caribbean (WB)",
    "Latin America and the Caribbean (SDG)",
    "Middle East and North Africa (WB)",
    "North America (WB)",
    "Northern Africa and Western Asia (SDG)",
    "Oceania (excluding Australia and New Zealand) (SDG)",
    "South Asia (WB)",
    "Sub-Saharan Africa (SDG)",
    "Sub-Saharan Africa (WB)",
    "High-income countries"
]

df_ylit = df_ylit[~df_ylit["country"].isin(remove_list)]

In [335]:
df_ylit[["youth_literacy_m", "youth_literacy_f"]] = (
    df_ylit.groupby("code")[["youth_literacy_m", "youth_literacy_f"]]
    .apply(lambda x: x.ffill().bfill())
    .reset_index(level=0, drop=True)
)

In [336]:
df_ylit.loc[(df_ylit["country"] == "Djibouti") & (df_ylit["year"] == 2006), "youth_literacy_m"] = 89.5

In [337]:
df_ylit.shape

(1211, 6)

In [338]:
df_ylit.to_csv("../data/processed/youth_literacy_rate_p.csv", index = False)

## Illiterate Population

In [339]:
df_ip = pd.read_csv("../data/un_processed/illiterate_population.csv")

In [340]:
df_ip.columns

Index(['entity', 'code', 'year', 'illiteracy_rate', 'literacy_rate'], dtype='str')

In [341]:
df_ip.columns = ['country', 'code', 'year', 'illiteracy_rate', 'literacy_rate']

In [342]:
df_ip.columns

Index(['country', 'code', 'year', 'illiteracy_rate', 'literacy_rate'], dtype='str')

In [343]:
df_ip.isnull().sum()

country              0
code               733
year                 0
illiteracy_rate      0
literacy_rate        0
dtype: int64

In [344]:
remove_list = [
    "World",
    "Low-income countries",
    "Lower-middle-income countries",
    "Upper-middle-income countries",
    "Middle-income countries",
    "Central and Southern Asia (SDG)",
    "East Asia and Pacific (WB)",
    "Eastern and South-Eastern Asia (SDG)",
    "Europe and Central Asia (WB)",
    "Europe and Northern America (SDG)",
    "Latin America and Caribbean (WB)",
    "Latin America and the Caribbean (SDG)",
    "Middle East and North Africa (WB)",
    "North America (WB)",
    "Northern Africa and Western Asia (SDG)",
    "Oceania (excluding Australia and New Zealand) (SDG)",
    "South Asia (WB)",
    "Sub-Saharan Africa (SDG)",
    "Sub-Saharan Africa (WB)",
    "High-income countries",
    "Western Europe (Buringh and van Zanden)"
]

df_ip = df_ip[~df_ip["country"].isin(remove_list)]

In [345]:
df_ip.isnull().sum()

country            0
code               0
year               0
illiteracy_rate    0
literacy_rate      0
dtype: int64

In [346]:
df_ip[df_ip["code"].isna()]

Empty DataFrame
Columns: [country, code, year, illiteracy_rate, literacy_rate]
Index: []

In [347]:
df_ip.shape

(1267, 5)

In [348]:
df_ip.to_csv("../data/processed/illiterate_population_p.csv", index = False)

## GDP per Capita

In [349]:
df_gc = pd.read_csv("../data/un_processed/GDP_per_capita.csv")

In [350]:
df_gc.columns

Index(['entity', 'code', 'year', 'ny_gdp_pcap_pp_kd', 'owid_region'], dtype='str')

In [351]:
df_gc.columns = ['country', 'code', 'year', 'gdp_pcap', 'region']

In [352]:
df_gc.isnull().sum()

country       0
code          0
year          0
gdp_pcap      0
region      455
dtype: int64

In [353]:
df_gc[df_gc["region"].isna()]

                         country      code  year    gdp_pcap region
1793  East Asia and Pacific (WB)    WB_EAP  1990   5756.0933    NaN
1794  East Asia and Pacific (WB)    WB_EAP  1991   5988.0327    NaN
1795  East Asia and Pacific (WB)    WB_EAP  1992   6222.9340    NaN
1796  East Asia and Pacific (WB)    WB_EAP  1993   6469.8840    NaN
1797  East Asia and Pacific (WB)    WB_EAP  1994   6784.1530    NaN
...                          ...       ...   ...         ...    ...
7165                       World  OWID_WRL  2020  18811.4940    NaN
7166                       World  OWID_WRL  2021  19866.7680    NaN
7167                       World  OWID_WRL  2022  20409.4410    NaN
7168                       World  OWID_WRL  2023  20918.3050    NaN
7169                       World  OWID_WRL  2024  21405.1170    NaN

[455 rows x 5 columns]

In [354]:
remove_list = [
    "World",
    "Low-income countries",
    "Lower-middle-income countries",
    "Upper-middle-income countries",
    "Middle-income countries",
    "Central and Southern Asia (SDG)",
    "East Asia and Pacific (WB)",
    "Eastern and South-Eastern Asia (SDG)",
    "Europe and Central Asia (WB)",
    "Europe and Northern America (SDG)",
    "Latin America and Caribbean (WB)",
    "Latin America and the Caribbean (SDG)",
    "Middle East and North Africa (WB)",
    "North America (WB)",
    "Northern Africa and Western Asia (SDG)",
    "Oceania (excluding Australia and New Zealand) (SDG)",
    "South Asia (WB)",
    "Sub-Saharan Africa (SDG)",
    "Sub-Saharan Africa (WB)",
    "High-income countries",
    "Western Europe (Buringh and van Zanden)"
]

df_gc = df_gc[~df_gc["country"].isin(remove_list)]

In [355]:
df_gc.isnull().sum()

country      0
code         0
year         0
gdp_pcap     0
region      70
dtype: int64

In [356]:
df_gc[df_gc["region"].isna()]

,country,code,year,gdp_pcap,region
2143,European Union (27),OWID_EU27,1990,33420.543,NaN
2144,European Union (27),OWID_EU27,1991,33581.098,NaN
2145,European Union (27),OWID_EU27,1992,33679.790,NaN
2146,European Union (27),OWID_EU27,1993,33378.280,NaN
2147,European Union (27),OWID_EU27,1994,34195.840,NaN
...,...,...,...,...,...
4305,"Middle East, North Africa, Afghanistan and Pak...",WB_MENAP,2020,13244.126,NaN
4306,"Middle East, North Africa, Afghanistan and Pak...",WB_MENAP,2021,13650.496,NaN
4307,"Middle East, North Africa, Afghanistan and Pak...",WB_MENAP,2022,14243.885,NaN
4308,"Middle East, North Africa, Afghanistan and Pak...",WB_MENAP,2023,14296.296,NaN
4309,"Middle East, North Africa, Afghanistan and Pak...",WB_MENAP,2024,14355.141,NaN

In [357]:
df_gc = df_gc.dropna(subset=['region'])

In [358]:
df_gc[df_gc["region"].isna()]

Empty DataFrame
Columns: [country, code, year, gdp_pcap, region]
Index: []

In [359]:
df_gc.shape

(6785, 5)

In [360]:
df_gc.to_csv("../data/processed/GDP_per_capita_p.csv", index = False)

## Average years of schooling

In [361]:
df_sc = pd.read_csv("../data/un_processed/years_of_schooling.csv")

In [362]:
df_sc.columns

Index(['entity', 'code', 'year', 'literacy_rate',
       'mf_youth_and_adults__15_64_years__average_years_of_education',
       'population_historical', 'owid_region'],
      dtype='str')

In [363]:
df_sc.columns = ['country', 'code', 'year', 'literacy_rate', 'avg_years_of_education', 'population', 'region']

In [364]:
df_sc.isnull().sum()

country                      0
code                       890
year                         0
literacy_rate             3365
avg_years_of_education    1697
population                 605
region                     893
dtype: int64

In [365]:
remove_list = [
    "World",
    "Low-income countries",
    "Lower-middle-income countries",
    "Upper-middle-income countries",
    "Middle-income countries",
    "Central and Southern Asia (SDG)",
    "East Asia and Pacific (WB)",
    "Eastern and South-Eastern Asia (SDG)",
    "Europe and Central Asia (WB)",
    "Europe and Northern America (SDG)",
    "Latin America and Caribbean (WB)",
    "Latin America and the Caribbean (SDG)",
    "Middle East and North Africa (WB)",
    "North America (WB)",
    "Northern Africa and Western Asia (SDG)",
    "Oceania (excluding Australia and New Zealand) (SDG)",
    "South Asia (WB)",
    "Sub-Saharan Africa (SDG)",
    "Sub-Saharan Africa (WB)",
    "High-income countries",
    "Western Europe (Buringh and van Zanden)"
]

df_sc = df_sc[~df_sc["country"].isin(remove_list)]

In [366]:
df_sc.isnull().sum()

country                      0
code                       157
year                         0
literacy_rate             3365
avg_years_of_education     964
population                   5
region                     160
dtype: int64

In [367]:
df_sc.loc[(df_sc["country"] == "Africa"), "region"] = "Africa"

In [368]:
df_sc.loc[(df_sc["country"] == "Africa"), "code"] = "Afr"

In [369]:
df_sc.columns

Index(['country', 'code', 'year', 'literacy_rate', 'avg_years_of_education',
       'population', 'region'],
      dtype='str')

In [370]:
df_sc.isnull().sum()

country                      0
code                       126
year                         0
literacy_rate             3365
avg_years_of_education     964
population                   5
region                     129
dtype: int64

In [371]:
df_sc.to_csv("years_of_schooling.csv", index = False)

In [372]:
df_sc["literacy_rate"] = df_sc.groupby("country")["literacy_rate"].ffill()
df_sc["literacy_rate"] = df_sc.groupby("country")["literacy_rate"].bfill()
df_sc["avg_years_of_education"] = df_sc.groupby("country")["avg_years_of_education"].transform(lambda x: x.fillna(x.median()))

In [373]:
df_sc["literacy_rate"] = df_sc.groupby("region")["literacy_rate"].transform(lambda x: x.fillna(x.median()))

In [374]:
global_median = df_sc["avg_years_of_education"].median()

df_sc["avg_years_of_education"] = (
    df_sc.groupby("country")["avg_years_of_education"]
    .transform(lambda x: x.fillna(x.median()))
    .fillna(global_median)
)

In [375]:
df_sc.shape

(4632, 7)

In [376]:
df_sc.isnull().sum()

country                     0
code                      126
year                        0
literacy_rate             129
avg_years_of_education      0
population                  5
region                    129
dtype: int64

In [377]:
df_sc = df_sc.dropna(subset=['region'])

In [378]:
df_sc[df_sc["literacy_rate"].isna()]

Empty DataFrame
Columns: [country, code, year, literacy_rate, avg_years_of_education, population, region]
Index: []

In [379]:
df_sc.to_csv("../data/processed/years_of_schooling_p.csv", index = False)

# Outlier Detection

## Adult Literacy rate

In [380]:
df_alit.head()

       country code  year  adult_literacy
0  Afghanistan  AFG  1979        18.00000
1  Afghanistan  AFG  2011        31.00000
2  Afghanistan  AFG  2015        33.75384
3  Afghanistan  AFG  2021        37.00000
4      Albania  ALB  2001        99.00000

In [381]:
Q1 = df_alit['adult_literacy'].quantile(0.25)
Q3 = df_alit['adult_literacy'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [382]:
import plotly.express as px
fig = px.box(df_alit, y="adult_literacy")
fig.show()

## Youth Literacy Rate

In [383]:
Q1 = df_ylit[['youth_literacy_m', 'youth_literacy_f']].quantile(0.25)
Q3 = df_ylit[['youth_literacy_m', 'youth_literacy_f']].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
print(upper_bound, lower_bound)
fig = px.box(df_ylit, y=['youth_literacy_m', 'youth_literacy_f'])
fig.show()

youth_literacy_m    115.5
youth_literacy_f    124.5
dtype: float64 youth_literacy_m    71.5
youth_literacy_f    56.5
dtype: float64

## Illeterate Population

In [384]:
df_ip.head()

       country code  year  illiteracy_rate  literacy_rate
0  Afghanistan  AFG  1950        97.000000        3.00000
1  Afghanistan  AFG  1979        82.000000       18.00000
2  Afghanistan  AFG  2011        69.000000       31.00000
3  Afghanistan  AFG  2015        66.246155       33.75384
4  Afghanistan  AFG  2021        63.000000       37.00000

In [385]:
Q1 = df_ip[['literacy_rate', 'illiteracy_rate']].quantile(0.25)
Q3 = df_ip[['literacy_rate', 'illiteracy_rate']].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [386]:
fig = px.box(df_ip, y=['literacy_rate', 'illiteracy_rate'])
fig.show()

## GDP per Capita

In [387]:
df_gc.head()

       country code  year   gdp_pcap region
0  Afghanistan  AFG  2000  1617.8264   Asia
1  Afghanistan  AFG  2001  1454.1108   Asia
2  Afghanistan  AFG  2002  1774.3087   Asia
3  Afghanistan  AFG  2003  1815.9282   Asia
4  Afghanistan  AFG  2004  1776.9182   Asia

In [388]:
Q1 = df_gc['gdp_pcap'].quantile(0.25)
Q3 = df_gc['gdp_pcap'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [389]:
fig = px.box(df_gc, y=['gdp_pcap'])
fig.show()

## Average Years of schooling

In [390]:
df_sc.head()

,country,code,year,literacy_rate,avg_years_of_education,population,region
0,Afghanistan,AFG,1870,3.0,0.01,4101170.0,Asia
1,Afghanistan,AFG,1875,3.0,0.01,4193635.0,Asia
2,Afghanistan,AFG,1880,3.0,0.01,4288021.0,Asia
3,Afghanistan,AFG,1885,3.0,0.01,4384343.0,Asia
4,Afghanistan,AFG,1890,3.0,0.01,4482635.0,Asia

In [391]:
Q1 = df_sc[['literacy_rate', 'avg_years_of_education', 'population']].quantile(0.25)
Q1 = df_sc[['literacy_rate', 'avg_years_of_education', 'population']].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [392]:
fig = px.box(df_sc, y='literacy_rate')
fig.show()

In [393]:
fig = px.box(df_sc, y='avg_years_of_education')
fig.show()

In [394]:
fig = px.box(df_sc, y='population')
fig.show()

# Creating Data from for Implementation

## df_literacy(Merging adult_literacy and youth_literacy)

In [395]:
df_lit = pd.merge(df_alit, df_ylit, on = ['country','code','year'], how = 'outer')

In [396]:
df_lit.info()

<class 'pandas.DataFrame'>
RangeIndex: 1228 entries, 0 to 1227
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   country           1228 non-null   str
 1   code              1228 non-null   str
 2   year              1228 non-null   int64
 3   adult_literacy    948 non-null    float64
 4   youth_literacy_m  1211 non-null   float64
 5   youth_literacy_f  1211 non-null   float64
 6   region            1211 non-null   str
dtypes: float64(3), int64(1), str(3)
memory usage: 67.3 KB

In [397]:
cols = ["adult_literacy", "youth_literacy_m", "youth_literacy_f"]
# ffill per country
df_lit[cols] = df_lit.groupby("country")[cols].transform(lambda x: x.ffill())
# bfill per country (catches remaining NAs at the start of a group)
df_lit[cols] = df_lit.groupby("country")[cols].transform(lambda x: x.bfill())

In [398]:
df_lit[df_lit.isnull().any(axis=1)]

,country,code,year,adult_literacy,youth_literacy_m,youth_literacy_f,region
22,Antigua and Barbuda,ATG,2001,99.00000,NaN,NaN,NaN
276,Cuba,CUB,1981,98.00000,100.00000,100.00000,NaN
290,Djibouti,DJI,2006,NaN,89.50000,51.81000,Africa
316,East Timor,TLS,2001,38.00000,87.25000,83.71000,NaN
317,East Timor,TLS,2007,51.00000,87.25000,83.71000,NaN
402,Fiji,FJI,2021,NaN,96.11000,99.41343,Oceania
403,French Guiana,GUF,1982,83.00000,NaN,NaN,NaN
512,Iran,IRN,2002,77.00000,96.00000,91.00000,NaN
635,Mali,MLI,2003,24.00000,32.00000,17.00000,NaN
657,Mauritius,MUS,2012,92.00000,98.00000,99.00000,NaN
658,Mauritius,MUS,2013,91.00000,98.00000,99.00000,NaN
659,Mauritius,MUS,2014,92.00000,98.00000,99.00000,NaN
660,Mauritius,MUS,2015,93.00000,98.00000,99.00000,NaN
661,Mauritius,MUS,2016,93.00000,98.00000,99.00000,NaN
707,Morocco,MAR,2014,76.00000,94.00000,88.00000,NaN
727,Nauru,NRU,2023,96.58654,NaN,NaN,NaN
917,Rwanda,RWA,1991,58.00000,60.00000,45.00000,NaN
928,Saint Lucia,LCA,2012,NaN,100.00000,99.96000,North America
995,Solomon Islands,SLB,1999,77.00000,NaN,NaN,NaN
1135,Turks and Caicos Islands,TCA,2020,NaN,99.88000,100.00000,North America
1136,Tuvalu,TUV,2019,NaN,99.09656,98.50764,Oceania
1183,Vanuatu,VUT,1999,74.00000,76.00000,68.00000,NaN

In [399]:
# Step 1: Build a country -> region mapping from existing non-null values
region_map = df_lit.dropna(subset=["region"]).drop_duplicates("country").set_index("country")["region"]

# Step 2: Fill missing region using the mapping
df_lit["region"] = df_lit["region"].fillna(df_lit["country"].map(region_map))

In [400]:
df_lit[cols] = df_lit.groupby("region")[cols].transform(lambda x: x.fillna(x.median()))

In [401]:
df_lit.dropna(how="any", inplace=True)

In [402]:
df_lit = df_lit[df_lit["year"] >= 1990]

In [403]:
df_lit.reset_index(drop=True, inplace=True)

In [404]:
df_lit.info()

<class 'pandas.DataFrame'>
RangeIndex: 1111 entries, 0 to 1110
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   country           1111 non-null   str
 1   code              1111 non-null   str
 2   year              1111 non-null   int64
 3   adult_literacy    1111 non-null   float64
 4   youth_literacy_m  1111 non-null   float64
 5   youth_literacy_f  1111 non-null   float64
 6   region            1111 non-null   str
dtypes: float64(3), int64(1), str(3)
memory usage: 60.9 KB

In [405]:
df_lit.head()

,country,code,year,adult_literacy,youth_literacy_m,youth_literacy_f,region
0,Afghanistan,AFG,2011,31.00000,62.00000,32.00000,Asia
1,Afghanistan,AFG,2015,33.75384,57.73505,25.48416,Asia
2,Afghanistan,AFG,2021,37.00000,71.00000,42.00000,Asia
3,Afghanistan,AFG,2022,37.00000,83.40000,44.17171,Asia
4,Albania,ALB,2001,99.00000,99.00000,99.00000,Europe

In [406]:
# Convert all string values to uppercase
df_lit = df_lit.apply(lambda x: x.str.upper() if x.dtype == "str" else x)

# Convert column names to uppercase
df_lit.columns = df_lit.columns.str.upper()

In [407]:
df_lit.duplicated().sum()

np.int64(0)

In [408]:
df_lit.to_csv("../data/implemented_data/literacy_p.csv", index = False)

## df_illiteracy(Illeterate population)

In [409]:
df_ip.info()

<class 'pandas.DataFrame'>
Index: 1267 entries, 0 to 2058
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   country          1267 non-null   str
 1   code             1267 non-null   str
 2   year             1267 non-null   int64
 3   illiteracy_rate  1267 non-null   float64
 4   literacy_rate    1267 non-null   float64
dtypes: float64(2), int64(1), str(2)
memory usage: 59.4 KB

In [410]:
df_ip.reset_index(drop=True, inplace=True)

In [411]:
# Convert all string values to uppercase
df_ip = df_ip.apply(lambda x: x.str.upper() if x.dtype == "str" else x)

# Convert column names to uppercase
df_ip.columns = df_ip.columns.str.upper()

In [412]:
df_ip = df_ip[df_ip["YEAR"] >= 1990]

In [413]:
df_ip.head()

       COUNTRY CODE  YEAR  ILLITERACY_RATE  LITERACY_RATE
2  AFGHANISTAN  AFG  2011        69.000000       31.00000
3  AFGHANISTAN  AFG  2015        66.246155       33.75384
4  AFGHANISTAN  AFG  2021        63.000000       37.00000
6      ALBANIA  ALB  2001         1.000000       99.00000
7      ALBANIA  ALB  2008         4.000000       96.00000

In [414]:
df_ip.info()

<class 'pandas.DataFrame'>
Index: 833 entries, 2 to 1266
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   COUNTRY          833 non-null    str
 1   CODE             833 non-null    str
 2   YEAR             833 non-null    int64
 3   ILLITERACY_RATE  833 non-null    float64
 4   LITERACY_RATE    833 non-null    float64
dtypes: float64(2), int64(1), str(2)
memory usage: 39.0 KB

In [415]:
df_ip.duplicated().sum()

np.int64(0)

In [416]:
df_ip.to_csv("../data/implemented_data/illeteracy_p.csv", index = False)

## df_gdp_schooling(Merging GDP per captia and average years of education)

In [417]:
df_gsc = pd.merge(df_gc, df_sc, on = ['country','code','year','region'], how = 'outer')

In [418]:
df_gsc.head()

,country,code,year,gdp_pcap,region,literacy_rate,avg_years_of_education,population
0,Afghanistan,AFG,1870,NaN,Asia,3.0,0.01,4101170.0
1,Afghanistan,AFG,1875,NaN,Asia,3.0,0.01,4193635.0
2,Afghanistan,AFG,1880,NaN,Asia,3.0,0.01,4288021.0
3,Afghanistan,AFG,1885,NaN,Asia,3.0,0.01,4384343.0
4,Afghanistan,AFG,1890,NaN,Asia,3.0,0.01,4482635.0

In [419]:
df_gsc = df_gsc[df_gsc["year"] >= 1990]

In [420]:
df_gsc.info()

<class 'pandas.DataFrame'>
Index: 6847 entries, 25 to 9795
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   country                 6847 non-null   str
 1   code                    6847 non-null   str
 2   year                    6847 non-null   int64
 3   gdp_pcap                6785 non-null   float64
 4   region                  6847 non-null   str
 5   literacy_rate           1554 non-null   float64
 6   avg_years_of_education  1554 non-null   float64
 7   population              1554 non-null   float64
dtypes: float64(4), int64(1), str(3)
memory usage: 481.4 KB

In [421]:
df_gsc["gdp_pcap"] = df_gsc.groupby("country")["gdp_pcap"].transform(lambda x: x.ffill().bfill())

In [422]:
df_gsc["gdp_pcap"] = df_gsc.groupby("region")["gdp_pcap"].transform(lambda x: x.ffill().bfill())

In [423]:
df_gsc[["literacy_rate", "avg_years_of_education", "population"]] = df_gsc.groupby("country")[["literacy_rate", "avg_years_of_education", "population"]].transform(lambda x: x.ffill().bfill())

In [424]:
df_gsc[["literacy_rate", "avg_years_of_education", "population"]] = df_gsc.groupby("region")[["literacy_rate", "avg_years_of_education", "population"]].transform(lambda x: x.mean())

In [425]:
df_gsc.info()

<class 'pandas.DataFrame'>
Index: 6847 entries, 25 to 9795
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   country                 6847 non-null   str
 1   code                    6847 non-null   str
 2   year                    6847 non-null   int64
 3   gdp_pcap                6847 non-null   float64
 4   region                  6847 non-null   str
 5   literacy_rate           6847 non-null   float64
 6   avg_years_of_education  6847 non-null   float64
 7   population              6847 non-null   float64
dtypes: float64(4), int64(1), str(3)
memory usage: 481.4 KB

In [426]:
df_gsc.duplicated().sum()

np.int64(0)

In [427]:
df_gsc.reset_index(drop=True, inplace=True)

In [428]:
# Convert all string values to uppercase
df_gsc = df_gsc.apply(lambda x: x.str.upper() if x.dtype == "str" else x)

# Convert column names to uppercase
df_gsc.columns = df_gsc.columns.str.upper()

In [429]:
df_gsc.to_csv("../data/implemented_data/avg_years_of_education_p.csv", index = False)