In [3]:
import pandas as pd
import pymysql as ps
from sqlalchemy import create_engine as ce

In [10]:
df_lit = pd.read_csv("../data/implemented_data/literacy_p.csv")
df_ill = pd.read_csv("../data/implemented_data/illeteracy_p.csv")
df_gsc = pd.read_csv("../data/implemented_data/avg_years_of_education_p.csv")

In [15]:
conn = ps.connect(
    host = "localhost",
    user = "root",
    password= "Mano_rootsql0481",
    database= "global_literacy_education_trends"
)

In [16]:
engine = ce(
    f"mysql+pymysql://root:Mano_rootsql0481@localhost:3306/global_literacy_education_trends",
    echo = False
)

In [17]:
df_lit.to_sql(
    'LITERACY',
    con=engine,
    if_exists='replace',
    index=False
)

1111

In [18]:
df_ill.to_sql(
    'ILLITERACY_POPULATION',
    con=engine,
    if_exists='replace',
    index=False
)

833

In [19]:
df_gsc.to_sql(
    'GDP_SCHOOLING',
    con=engine,
    if_exists='replace',
    index=False
)

6847

In [20]:
# Add composite primary keys (COUNTRY, YEAR) for the three tables
from sqlalchemy import text

def add_primary_key(table_name):
    with engine.begin() as connection:
        try:
            # Modify columns to NOT NULL before setting them as primary key
            connection.execute(text(f"ALTER TABLE {table_name} MODIFY COUNTRY VARCHAR(100) NOT NULL;"))
            connection.execute(text(f"ALTER TABLE {table_name} MODIFY YEAR INT NOT NULL;"))
            
            # Add the primary key
            connection.execute(text(f"ALTER TABLE {table_name} ADD PRIMARY KEY (COUNTRY, YEAR);"))
            print(f"Successfully added composite primary key for {table_name}")
        except Exception as e:
            print(f"Error adding primary key to {table_name}: {e}")

add_primary_key('LITERACY')
add_primary_key('ILLITERACY_POPULATION')
add_primary_key('GDP_SCHOOLING')

Successfully added composite primary key for LITERACY
Successfully added composite primary key for ILLITERACY_POPULATION
Successfully added composite primary key for GDP_SCHOOLING

# Executing Queries

### 1. Get top 5 countries with highest adult literacy in 2020.

In [22]:
query = """
SELECT COUNTRY, ADULT_LITERACY FROM LITERACY WHERE YEAR = 2020 ORDER BY ADULT_LITERACY DESC LIMIT 5;
"""
display(pd.read_sql(query, conn))

/var/folders/_x/xjprn7fn01v4sclwmkr7t81c0000gn/T/ipykernel_98057/645231331.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, conn))

        COUNTRY  ADULT_LITERACY
0       ARMENIA           100.0
1      MONGOLIA            99.0
2         SPAIN            99.0
3     PALESTINE            98.0
4  SAUDI ARABIA            98.0

### 2. Find countries where female youth literacy < 80%.

In [23]:
query = """
SELECT COUNTRY, YEAR, YOUTH_LITERACY_F FROM LITERACY WHERE YOUTH_LITERACY_F < 80;
"""
display(pd.read_sql(query, conn))

/var/folders/_x/xjprn7fn01v4sclwmkr7t81c0000gn/T/ipykernel_98057/1605081484.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, conn))

         COUNTRY  YEAR  YOUTH_LITERACY_F
0    AFGHANISTAN  2011          32.00000
1    AFGHANISTAN  2015          25.48416
2    AFGHANISTAN  2021          42.00000
3    AFGHANISTAN  2022          44.17171
4         ANGOLA  2001          63.00000
..           ...   ...               ...
244        YEMEN  2023          76.91698
245       ZAMBIA  1990          66.00000
246       ZAMBIA  1999          66.00000
247       ZAMBIA  2002          66.00000
248       ZAMBIA  2018          72.90992

[249 rows x 3 columns]

### 3. Average adult literacy per continent (owid region).

In [24]:
query = """
SELECT REGION, AVG(ADULT_LITERACY) AS AVG_ADULT_LITERACY FROM LITERACY GROUP BY REGION;
"""
display(pd.read_sql(query, conn))

/var/folders/_x/xjprn7fn01v4sclwmkr7t81c0000gn/T/ipykernel_98057/2076078491.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, conn))

          REGION  AVG_ADULT_LITERACY
0           ASIA           85.796006
1         EUROPE           97.419670
2         AFRICA           60.235767
3  SOUTH AMERICA           92.778873
4  NORTH AMERICA           86.870273
5        OCEANIA           92.858361

### 4. Countries with illiteracy % > 20% in 2000.

In [25]:
query = """
SELECT COUNTRY, `ILLITERACY%` FROM ILLITERACY_POPULATION WHERE YEAR = 2000 AND `ILLITERACY%` > 20;
"""
display(pd.read_sql(query, conn))

/var/folders/_x/xjprn7fn01v4sclwmkr7t81c0000gn/T/ipykernel_98057/1779877735.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, conn))

                     COUNTRY  ILLITERACY%
0                    BURUNDI         41.0
1                   CAMEROON         32.0
2   CENTRAL AFRICAN REPUBLIC         49.0
3                       CHAD         74.0
4                    COMOROS         32.0
5              COTE D'IVOIRE         51.0
6                     GAMBIA         63.0
7                      GHANA         42.0
8              GUINEA-BISSAU         59.0
9                       IRAQ         26.0
10                      LAOS         30.0
11                MADAGASCAR         29.0
12                MAURITANIA         49.0
13          PAPUA NEW GUINEA         43.0
14                    RWANDA         35.0
15              SAUDI ARABIA         21.0
16                     SUDAN         39.0
17                      TOGO         47.0

### 5. Trend of illiteracy % for India (2000–2020).

In [26]:
query = """
SELECT YEAR, `ILLITERACY%` FROM ILLITERACY_POPULATION WHERE COUNTRY = 'India' AND YEAR BETWEEN 2000 AND 2020 ORDER BY YEAR;
"""
display(pd.read_sql(query, conn))

/var/folders/_x/xjprn7fn01v4sclwmkr7t81c0000gn/T/ipykernel_98057/3395873270.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, conn))

   YEAR  ILLITERACY%
0  2001         39.0
1  2006         37.0
2  2011         31.0

### 6. Top 10 countries with largest illiterate population in the last year.

In [27]:
query = """
SELECT i.COUNTRY, i.YEAR, (i.ILLITERACY_RATE / 100 * g.POPULATION) AS ILLITERATE_POPULATION FROM ILLITERACY_POPULATION i JOIN GDP_SCHOOLING g ON i.COUNTRY = g.COUNTRY AND i.YEAR = g.YEAR WHERE i.YEAR = (SELECT MAX(YEAR) FROM ILLITERACY_POPULATION) ORDER BY ILLITERATE_POPULATION DESC LIMIT 10;
"""
display(pd.read_sql(query, conn))

/var/folders/_x/xjprn7fn01v4sclwmkr7t81c0000gn/T/ipykernel_98057/1860693964.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, conn))

                COUNTRY  YEAR  ILLITERATE_POPULATION
0                 INDIA  2023           1.509921e+07
1               SENEGAL  2023           1.122368e+07
2             SRI LANKA  2023           5.871916e+06
3                JORDAN  2023           4.194226e+06
4               TUNISIA  2023           3.109353e+06
5           EL SALVADOR  2023           2.692104e+06
6               BAHRAIN  2023           1.677690e+06
7  UNITED ARAB EMIRATES  2023           1.677690e+06
8               GEORGIA  2023           3.728891e+05
9               VANUATU  2023           3.381717e+05

### 7. Find countries with avg_years_schooling > 7 and gdp_per_capita < 5000.

In [28]:
query = """
SELECT COUNTRY, YEAR, AVG_YEARS_OF_EDUCATION, GDP_PCAP FROM GDP_SCHOOLING WHERE AVG_YEARS_OF_EDUCATION > 7 AND GDP_PCAP < 5000;
"""
display(pd.read_sql(query, conn))

/var/folders/_x/xjprn7fn01v4sclwmkr7t81c0000gn/T/ipykernel_98057/842202865.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, conn))

                   COUNTRY  YEAR  AVG_YEARS_OF_EDUCATION   GDP_PCAP
0                  ALBANIA  1991                9.569358  4027.9055
1                  ALBANIA  1992                9.569358  3761.1555
2                  ALBANIA  1993                9.569358  4145.9200
3                  ALBANIA  1994                9.569358  4517.7990
4                  ALBANIA  1997                9.569358  4943.0040
5   BOSNIA AND HERZEGOVINA  1990                9.569358  2413.9482
6   BOSNIA AND HERZEGOVINA  1991                9.569358  2183.5352
7   BOSNIA AND HERZEGOVINA  1992                9.569358  2150.9197
8   BOSNIA AND HERZEGOVINA  1993                9.569358  2281.8992
9   BOSNIA AND HERZEGOVINA  1994                9.569358  2657.8140
10  BOSNIA AND HERZEGOVINA  1995                9.569358  3090.3910
11  BOSNIA AND HERZEGOVINA  1996                9.569358  4569.0015

### 8. Rank countries by GDP per schooling for the year 2020.

In [29]:
query = """
SELECT COUNTRY, `GDP PER SCHOOLING YEAR` FROM GDP_SCHOOLING WHERE YEAR = 2020 ORDER BY `GDP PER SCHOOLING YEAR` DESC;
"""
display(pd.read_sql(query, conn))

/var/folders/_x/xjprn7fn01v4sclwmkr7t81c0000gn/T/ipykernel_98057/1160962851.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, conn))

                          COUNTRY  GDP PER SCHOOLING YEAR
0                       SINGAPORE            17862.252023
1                           QATAR            15884.626305
2                      LUXEMBOURG            13570.986971
3                         BERMUDA            13301.374966
4                          BRUNEI            12373.458047
..                            ...                     ...
200                    MOZAMBIQUE              348.917691
201                       SOMALIA              332.242130
202  DEMOCRATIC REPUBLIC OF CONGO              323.906087
203      CENTRAL AFRICAN REPUBLIC              270.488290
204                       BURUNDI              245.309262

[205 rows x 2 columns]

### 9. Find global average schooling years per year.

In [30]:
query = """
SELECT YEAR, AVG(AVG_YEARS_OF_EDUCATION) AS GLOBAL_AVG_SCHOOLING FROM GDP_SCHOOLING GROUP BY YEAR ORDER BY YEAR;
"""
display(pd.read_sql(query, conn))

/var/folders/_x/xjprn7fn01v4sclwmkr7t81c0000gn/T/ipykernel_98057/3533856016.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, conn))

    YEAR  GLOBAL_AVG_SCHOOLING
0   1990              6.443218
1   1991              6.459722
2   1992              6.443004
3   1993              6.443004
4   1994              6.443484
5   1995              6.435686
6   1996              6.455935
7   1997              6.492605
8   1998              6.480612
9   1999              6.492605
10  2000              6.468484
11  2001              6.490763
12  2002              6.483446
13  2003              6.494341
14  2004              6.494341
15  2005              6.469458
16  2006              6.495207
17  2007              6.493389
18  2008              6.503816
19  2009              6.525153
20  2010              6.502686
21  2011              6.525153
22  2012              6.528622
23  2013              6.516258
24  2014              6.516258
25  2015              6.491462
26  2016              6.513536
27  2017              6.516258
28  2018              6.516258
29  2019              6.516989
30  2020              6.491462
31  2021              6.516258
32  2022              6.516258
33  2023              6.515659
34  2024              6.511063

### 10. List top 10 countries in 2020 with highest GDP per capita but lowest average years of schooling(less than 6).

In [31]:
query = """
SELECT COUNTRY, GDP_PCAP, AVG_YEARS_OF_EDUCATION FROM GDP_SCHOOLING WHERE YEAR = 2020 AND AVG_YEARS_OF_EDUCATION < 6 ORDER BY GDP_PCAP DESC LIMIT 10;
"""
display(pd.read_sql(query, conn))

/var/folders/_x/xjprn7fn01v4sclwmkr7t81c0000gn/T/ipykernel_98057/2453640764.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, conn))

       COUNTRY   GDP_PCAP  AVG_YEARS_OF_EDUCATION
0    AUSTRALIA  57260.465                5.715524
1  NEW ZEALAND  46266.395                5.715524
2    VENEZUELA  32038.773                5.971914
3   SEYCHELLES  30056.200                4.201922
4      URUGUAY  27788.186                5.971914
5        CHILE  26248.562                5.971914
6    ARGENTINA  23877.094                5.971914
7    MAURITIUS  22258.387                4.201922
8       GUYANA  19234.130                5.971914
9     SURINAME  19091.361                5.971914

### 11. Show countries where the illiterate population is high despite having more than 10 average years of schooling.

In [43]:
query = """
SELECT 
    COUNTRY,
    AVG_YEARS_OF_EDUCATION,
    POPULATION,
    (POPULATION * (100 - LITERACY_RATE) / 100) AS ILLITERATE_POPULATION
FROM GDP_SCHOOLING
WHERE AVG_YEARS_OF_EDUCATION > 6.5
AND (POPULATION * (100 - LITERACY_RATE) / 100) > 1000000
ORDER BY ILLITERATE_POPULATION DESC;
"""
display(pd.read_sql(query, conn))

/var/folders/_x/xjprn7fn01v4sclwmkr7t81c0000gn/T/ipykernel_98057/3671072612.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, conn))

,COUNTRY,AVG_YEARS_OF_EDUCATION,POPULATION,ILLITERATE_POPULATION
0,ANTIGUA AND BARBUDA,6.662325,2.692104e+07,3.887501e+06
1,ANTIGUA AND BARBUDA,6.662325,2.692104e+07,3.887501e+06
2,ANTIGUA AND BARBUDA,6.662325,2.692104e+07,3.887501e+06
3,ANTIGUA AND BARBUDA,6.662325,2.692104e+07,3.887501e+06
4,ANTIGUA AND BARBUDA,6.662325,2.692104e+07,3.887501e+06
...,...,...,...,...
1012,UNITED STATES VIRGIN ISLANDS,6.662325,2.692104e+07,3.887501e+06
1013,UNITED STATES VIRGIN ISLANDS,6.662325,2.692104e+07,3.887501e+06
1014,UNITED STATES VIRGIN ISLANDS,6.662325,2.692104e+07,3.887501e+06
1015,UNITED STATES VIRGIN ISLANDS,6.662325,2.692104e+07,3.887501e+06
1016,UNITED STATES VIRGIN ISLANDS,6.662325,2.692104e+07,3.887501e+06

### 12. Compare literacy rates and GDP per capita growth for a selected country over the last 20 years. (India)

In [33]:
query = """
SELECT l.YEAR, l.ADULT_LITERACY, g.GDP_PCAP FROM LITERACY l JOIN GDP_SCHOOLING g ON l.COUNTRY = g.COUNTRY AND l.YEAR = g.YEAR WHERE l.COUNTRY = 'India' AND l.YEAR >= (SELECT MAX(YEAR) - 20 FROM LITERACY) ORDER BY l.YEAR;
"""
display(pd.read_sql(query, conn))

/var/folders/_x/xjprn7fn01v4sclwmkr7t81c0000gn/T/ipykernel_98057/762638287.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, conn))

   YEAR  ADULT_LITERACY   GDP_PCAP
0  2006            63.0  4129.7783
1  2011            69.0  5249.5493
2  2016            69.0  6940.6260
3  2020            69.0  7399.5310
4  2022            76.0  8594.3920
5  2023            82.0  9301.7560

### 13. Show the difference between youth literacy male and female rates for countries with GDP per capita above $30,000 in 2020.

In [34]:
query = """
SELECT l.COUNTRY, g.GDP_PCAP, l.YOUTH_LITERACY_M, l.YOUTH_LITERACY_F, ABS(l.YOUTH_LITERACY_M - l.YOUTH_LITERACY_F) AS GENDER_GAP FROM LITERACY l JOIN GDP_SCHOOLING g ON l.COUNTRY = g.COUNTRY AND l.YEAR = g.YEAR WHERE l.YEAR = 2020 AND g.GDP_PCAP > 30000;
"""
display(pd.read_sql(query, conn))

/var/folders/_x/xjprn7fn01v4sclwmkr7t81c0000gn/T/ipykernel_98057/143467974.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  display(pd.read_sql(query, conn))

        COUNTRY    GDP_PCAP  YOUTH_LITERACY_M  YOUTH_LITERACY_F  GENDER_GAP
0        KUWAIT   49372.820              99.0             100.0         1.0
1          OMAN   37560.600             100.0             100.0         0.0
2  SAUDI ARABIA   57420.734             100.0              99.0         1.0
3     SINGAPORE  115893.040             100.0             100.0         0.0
4         SPAIN   41553.450              99.0             100.0         1.0